repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.17.0
    hooks:
      - id: eslint
        additional_dependencies:
          - babel-eslint@10.1.0
          - eslint-config-react-app@5.2.1
          - eslint-loader@3.0.3
          - eslint-plugin-flowtype@4.6.0
          - eslint-plugin-import@2.20.1
          - eslint-plugin-jsx-a11y@6.2.3
          - eslint-plugin-promise@4.2.1
          - eslint-plugin-react-hooks@2.5.1
          - eslint-plugin-react@7.19.0
          - eslint-plugin-unused-imports@1.0.1
          - eslint@7.17.0
