export { default as TestSVG } from "./assets/SVG.svg";
export { default as Ice } from "./assets/ice.svg";
export { default as OffIce } from "./assets/off-ice.svg";
export { default as ExclamationCircle } from "./assets/exclamation-circle.svg";
export { default as Close } from "./assets/close.svg";
export { default as AccountCircle } from "./assets/account-circle.svg";
export { default as Calendar } from "./assets/calendar.svg";
export { default as ChevronLeft } from "./assets/chevron-left.svg";
export { default as ChevronRight } from "./assets/chevron-right.svg";
export { default as EisbukLogo } from "./assets/logo.svg";
export { default as Cog } from "./assets/cog.svg";
export { default as User } from "./assets/user.svg";
export { default as Users } from "./assets/users.svg";
export { default as ClipboardList } from "./assets/clipboard-list.svg";
export { default as ClipboardCheck } from "./assets/clipboard-check.svg";
export { default as DocumentDuplicate } from "./assets/document-duplicate.svg";
export { default as Printer } from "./assets/printer.svg";
export { default as Copy } from "./assets/copy.svg";
export { default as PlusCircle } from "./assets/plus-circle.svg";
export { default as Trash } from "./assets/trash.svg";
export { default as Pencil } from "./assets/pencil.svg";
export { default as Cake } from "./assets/cake.svg";
export { default as Mail } from "./assets/mail.svg";
export { default as Phone } from "./assets/phone.svg";
export { default as ShieldCheck } from "./assets/shield-check.svg";
export { default as CheckCircle } from "./assets/check-circle.svg";
export { default as XCircle } from "./assets/x-circle.svg";
export { default as QuestionMarkCircle } from "./assets/question-mark-circle.svg";
export { default as Annotation } from "./assets/annotation.svg";
export { default as Eye } from "./assets/eye.svg";
export { default as EyeOff } from "./assets/eye-off.svg";
export { default as Identification } from "./assets/identification.svg";
export { default as FolderOpen } from "./assets/folder-open.svg";
export { default as Plus } from "./assets/plus.svg";
export { default as Minus } from "./assets/minus.svg";
export { default as Google } from "./assets/google.svg";
export { default as Key } from "./assets/key.svg";
export { default as PowerCircle } from "./assets/power-circle.svg";
export { default as UserGroup } from "./assets/user-group.svg";

// Export a standard type for SVG component, to be used throughout the app
import type { SVGComponent } from "./types";
export type { SVGComponent };
