#! YAML library files must be named *.lib.yml
#@ load("cache.lib.yml", "cache_node", "cache_cypress")
#@ load("rush.lib.yml", "rush_add_path", "rush_update", "rush_build")
#@ load("secrets.lib.yml", "check_secrets")
#@ load("rclone.lib.yml", "install_rclone")
#@ load("rclone.lib.yml", "install_gcloud_credentials")
#@ load("rclone.lib.yml", "set_results_destination")
#@ load("storybook.lib.yml", "build_storybook")

name: OnPush

"on":
  - push

jobs:

  cypress-run:
    name: Cypress browser tests
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        #! Define 6 values for two vars to get 36 runs
        dummy1: [1,2,3,4,5,6]
        dummy2: [1,2,3,4,5,6]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - #@ cache_cypress()
      - #@ rush_add_path()
      - #@ rush_update()
      - #@ rush_build()
      - name: Build app
        run: cd packages/client && rushx build:test
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: rush emulators:start

          #! For some reason, this action can also install everything, which doesn't work well with pnpm
          #! Anyway we're using our own instalation as it is, so just skipping this part
          install: false

          working-directory: packages/e2e
          wait-on: http://localhost:8080, http://localhost:5000

          #! skip recording if no 'secrets.CYPRESS_KEY' found
          #! we're doing this to allow dependabot to run cypress tests without failing on account of CYPRESS_KEY
          record: ${{ secrets.CYPRESS_KEY != 0 }}

          config-file: cypress-ci.json
        env:
          #! pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_KEY }}

          #! pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - #@ check_secrets()
      - name: Coveralls
        uses: coverallsapp/github-action@master
        if: steps.has_secret.outputs.HAS_SECRETS
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: packages/e2e/coverage/lcov.info
          base-path: packages/e2e
          flag-name: run-cypress
          parallel: true
      - #@ install_gcloud_credentials()
      - #@ set_results_destination()
      - #@ install_rclone()
      - name: Copy test results to gcloud
        if: (success() || failure()) && steps.has_secret.outputs.HAS_SECRETS
        run: |
          rclone copy packages/e2e/reports/html/ gcloud:cypress-logs-bucket/${{ steps.results-destination.outputs.RESULTS_DESTINATION }}/ --log-level INFO
          rclone copy packages/e2e/coverage/ gcloud:cypress-logs-bucket/${{ steps.results-destination.outputs.RESULTS_DESTINATION }}/coverage-cypress --log-level INFO
      - name: Print gcloud url to view test results
        if: (success() || failure()) && steps.has_secret.outputs.HAS_SECRETS
        run: |
          mkdir result_tabs
          echo Check out test results at https://storage.googleapis.com/cypress-logs-bucket/${{ steps.results-destination.outputs.RESULTS_DESTINATION }}/index.html
          echo Check out coverage result: https://storage.googleapis.com/cypress-logs-bucket/${{ steps.results-destination.outputs.RESULTS_DESTINATION }}/coverage-cypress/index.html
          echo "[Check out test results](https://storage.googleapis.com/cypress-logs-bucket/${{ steps.results-destination.outputs.RESULTS_DESTINATION }}/index.html)" > result_tabs/cypress.md
          echo "[Check out coverage result](https://storage.googleapis.com/cypress-logs-bucket/${{ steps.results-destination.outputs.RESULTS_DESTINATION }}/coverage-cypress/lcov-report/index.html)" >> result_tabs/cypress.md
