#@ def check_secrets():
name: Check if secrets are available
id: has_secret
if: success() || failure()
run: '[ "${{ secrets.SENTRY_ORG }}" != "" ] && echo ::set-output name=HAS_SECRETS::true || echo ::set-output name=HAS_SECRETS::'
#@ end
