#@ def check_secrets():
name: Check if secrets are available
id: has_secret
if: success() || failure()
run: '[ "${{ secrets.CYPRESS_KEY }}" != "" ] && echo HAS_SECRETS=true >> $GITHUB_OUTPUT || echo HAS_SECRETS= >> $GITHUB_OUTPUT'
#@ end
