#@ load("cache.lib.yml", "cache_node", "cache_cypress")
#@ load("rush.lib.yml", "rush_add_path", "rush_update", "rush_build")
#@ load("secrets.lib.yml", "check_secrets")
#@ load("rclone.lib.yml", "install_rclone")
#@ load("rclone.lib.yml", "install_gcloud_credentials")
#@ load("rclone.lib.yml", "set_results_destination")

#@ def build_storybook(package_name):
name: #@ "Build storybook for %s" % (package_name)
runs-on: ubuntu-latest
timeout-minutes: 10
steps:
  - uses: actions/checkout@v2
    with:
      fetch-depth: 0
  - uses: actions/setup-node@v2
    with:
      node-version: "18"
  -  #@ cache_node()
  -  #@ rush_add_path()
  -  #@ rush_update()
  -  #@ rush_build()
  -  #@ check_secrets()
  - name: #@ "Build %s storybook" % (package_name)
    run: #@ "cd packages/%s && rushx build-storybook" % (package_name)
  - name: Publish storybook
    run: echo Publishing storybook to ${{ github.sha }}
  -  #@ install_gcloud_credentials()
  -  #@ set_results_destination()
  -  #@ install_rclone()
  - name: Copy test results to gcloud
    if: (success() || failure()) && steps.has_secret.outputs.HAS_SECRETS
    run: #@ "rclone copy packages/%s/storybook-static gcloud:cypress-logs-bucket/${{ steps.results-destination.outputs.RESULTS_DESTINATION }}/storybook-%s --log-level INFO" % (package_name, package_name)
  - name: Print gcloud url to view test results
    if: (success() || failure()) && steps.has_secret.outputs.HAS_SECRETS
    run: #@ "echo Check out %s storybook at https://storage.googleapis.com/cypress-logs-bucket/${{ steps.results-destination.outputs.RESULTS_DESTINATION }}/storybook-%s/index.html >> $GITHUB_STEP_SUMMARY" % (package_name, package_name)
#@ end
