#! YAML library files must be named *.lib.yml
#@ load("cache.lib.yml", "cache_node", "cache_cypress")

name: Storybook

"on":
  - pull_request

jobs:
  storybook:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - #@ cache_node()
      - name: Install rush
        run: npm install -g @microsoft/rush@5.63.1
      - name: Install and build packages
        run: rush update && rush build
      - name: Check if secrets are available
        id: has_secret
        run: '[ "${{ secrets.SENTRY_ORG }}" != "" ] && echo ::set-output name=HAS_SECRETS::true || echo ::set-output name=HAS_SECRETS::'
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        if: steps.has_secret.outputs.HAS_SECRETS
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMAUI_PROJECT_TOKEN }}
          workingDir: packages/client
          exitZeroOnChanges: true
          exitOnceUploaded: true
