#! YAML library files must be named *.lib.yml
#@ load("setup.lib.yml", "checkout")
#@ load("cache.lib.yml", "cache_node", "cache_cypress")
#@ load("rush.lib.yml", "rush_add_path", "rush_update", "rush_build")
#@ load("secrets.lib.yml", "check_secrets")

name: Chromatic Storybook

"on":
  - pull_request

jobs:
  storybook:
    name: Build storybook and push to Chromatic
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      -  #@ checkout(0)
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      -  #@ cache_node()
      -  #@ rush_add_path()
      -  #@ rush_update()
      -  #@ rush_build()
      -  #@ check_secrets()
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        if: steps.has_secret.outputs.HAS_SECRETS
        #! We expect this to fail with `Command failed with ENOENT: pnpm --version`
        continue-on-error: true
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMAUI_PROJECT_TOKEN }}
          workingDir: packages/client
          exitZeroOnChanges: true
          exitOnceUploaded: true
