name: Build and deploy preview

on:
  - push
  - pull_request

jobs:
  build_v14:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Cache node modules and firebase emulators
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            node_modules
            $HOME/.cache/firebase/emulators
          key: ${{ runner.os }}-modules-emulators-node14-v1-${{ hashFiles('**/yarn.lock') }}
      - name: Install and link packages
        run: yarn
      - name: Build app
        run: |
          yarn --cwd eisbuk-admin build | tee build.output
          echo "BUILD_STATS<<EOF" >> $GITHUB_ENV
          cat build.output|grep File\ sizes -A5 >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        env:
          REACT_APP_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          REACT_APP_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          REACT_APP_DATABASE_URL: ${{ secrets.DATABASE_URL }}
          REACT_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          REACT_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          REACT_APP_FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          REACT_APP_FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
          REACT_APP_SENTRY_DSN: ${{ secrets.SENTRY_IGORICE_DSN }}
          REACT_APP_SENTRY_ENVIRONMENT: staging
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      - name: Deploy preview channel
        id: deploy
        run: |
          set -e
          # Run the `deploy:preview` script, passing the current git branch to be used for the name
          # of the preview channel
          yarn --cwd eisbuk-admin deploy:preview -- ${GITHUB_REF_SLUG_URL:-dev} | tee deploy.output
          # To pass the info to a later task, use the $GITHUB_ENV file
          cat deploy.output | grep 'hosting:channel:.*https://'|sed -e "s/\x1b\[[0-9;]*m//g;s|.*(||;s|)[^h]*|=|" >> $GITHUB_ENV
          # documented here: https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_EISBUK }}
      - name: Find Comment
        uses: peter-evans/find-comment@v1
        if: ${{ github.event.pull_request.number }}
        id: findcomment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-includes: Deployed URLs

      - name: Add preview channel URL to comment on PR
        uses: peter-evans/create-or-update-comment@v1
        if: ${{ github.event.pull_request.number }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          comment-id: ${{ steps.findcomment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Deployed URLs:
              * Igorice: ${{ env.igorice }}
              * Eisbuk: ${{ env.eisbuk }}
            ```
            ${{ env.BUILD_STATS }}
            ```
          reactions: heart, hooray, laugh, rocket
          edit-mode: replace

  test_v14:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Cache node modules and firebase emulators
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            node_modules
            $HOME/.cache/firebase/emulators
          key: ${{ runner.os }}-modules-emulators-node14-v1-${{ hashFiles('**/yarn.lock') }}
      - name: Install and link packages
        run: yarn
      - name: Run tests
        run: yarn --cwd eisbuk-admin test:emulators:ci
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure() # Do not run on cancelled; run in all other cases
        with:
          name: JEST Tests
          path: eisbuk-admin/junit.xml
          reporter: jest-junit
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: eisbuk-admin/coverage/lcov.info

  run-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Cache node modules and firebase emulators
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            node_modules
            $HOME/.cache/firebase/emulators
          key: ${{ runner.os }}-modules-emulators-node14-v1-${{ hashFiles('**/yarn.lock') }}
      - name: Install and link packages
        run: yarn
      - name: Lint client app
        run: "yarn --cwd eisbuk-admin lint:strict"
      - name: Lint eisbuk-shared
        # Do not run on cancelled; run in all other cases
        if: success() || failure()
        run: "yarn --cwd eisbuk-shared lint:strict"
      - name: Lint the functions
        if: success() || failure()
        run: "yarn --cwd eisbuk-admin/functions lint:strict"
      - name: Typecheck client app
        if: success() || failure()
        run: "yarn --cwd eisbuk-admin typecheck"
      - name: Typecheck the functions
        if: success() || failure()
        run: "yarn --cwd eisbuk-admin/functions typecheck"

  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            node_modules
            $HOME/.cache/firebase/emulators
            $HOME/.cache/Cypress
            $HOME/Library/Caches/Cypress
          key: ${{ runner.os }}-modules-emulators-cypress-node14-v1-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn

      - name: Build app
        run: yarn --cwd eisbuk-admin build:test
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: yarn emulators:start
          working-directory: eisbuk-admin
          wait-on: http://localhost:8080, http://localhost:5000
          record: true
          config-file: cypress-ci.json
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_KEY }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create file with gcloud cretentials
        if: success() || failure()
        # To make sure the file contents are not manipulated by the github infrastructure
        # they're encoded using base64. Here we decode them.
        # A downside of this approach is that we don't get the default
        # protection in case of accidental printing of the secret file.
        run: echo "${{ secrets.GCLOUD_JSON_BASE64 }}" | base64 -d > .gcloud.json

      - name: Set destination of test results
        if: success() || failure()
        run: echo "::set-output name=RESULTS_DESTINATION::$(date +%Y-%m-%d)/${{ github.run_id }}"
        id: results-destination

      - name: Install rclone
        if: success() || failure()
        run: |
          curl https://rclone.org/install.sh | sudo bash
          mkdir -p ~/.config/rclone
          echo "${RCLONE_CONF}" > ~/.config/rclone/rclone.conf
        env:
          RCLONE_CONF: |
            [gcloud]
            type = google cloud storage
            service_account_file = ${{ github.workspace }}/.gcloud.json
            object_acl = publicRead
            bucket_acl = publicRead
            bucket_policy_only = true

      - name: Copy test results to gcloud
        if: success() || failure()
        run: |
          rclone copy eisbuk-admin/cypress/reports/html/ gcloud:cypress-logs-bucket/${{ steps.results-destination.outputs.RESULTS_DESTINATION }}/

      - name: Print gcloud url to view test results
        if: success() || failure()
        run: |
          mkdir result_tabs
          echo Check out test results at https://storage.googleapis.com/cypress-logs-bucket/${{ steps.results-destination.outputs.RESULTS_DESTINATION }}/index.html
          echo Check out test results at https://storage.googleapis.com/cypress-logs-bucket/${{ steps.results-destination.outputs.RESULTS_DESTINATION }}/index.html > result_tabs/cypress.md

      - name: "Create cypress browser logs summaries"
        if: success() || failure()
        # Create summeries
        uses: eisbuk/custom-check-summary@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILE_DIR: result_tabs
          SUMMARY_TITLE: "Cypress results"
