name: Build

on:
  - push
  - pull_request

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Cache node modules and firebase emulators
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            $HOME/.cache/firebase/emulators
          key: ${{ runner.os }}-modules-emulators-v12-${{ hashFiles('**/yarn.lock') }}
      - name: Install and link packages
        run: bash eisbuk-install.sh

  build_v14:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Build app
        run: yarn --cwd eisbuk-admin build

  test_v14:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: yarn --cwd eisbuk-admin test:ci

  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7"
          architecture: "x64"
      - uses: pre-commit/action@v2.0.0
