name: Build and deploy preview

on:
  - push
  - pull_request

jobs:
  build_v14:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Cache node modules and firebase emulators
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            $HOME/.cache/firebase/emulators
          key: ${{ runner.os }}-modules-emulators-v12-${{ hashFiles('**/yarn.lock') }}
      - name: Install and link packages
        run: yarn
      - name: Build app
        run: |
          yarn --cwd eisbuk-admin build | tee build.output
          echo "BUILD_STATS<<EOF" >> $GITHUB_ENV
          cat build.output|grep File\ sizes -A5 >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        env:
          REACT_APP_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          REACT_APP_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          REACT_APP_DATABASE_URL: ${{ secrets.DATABASE_URL }}
          REACT_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          REACT_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          REACT_APP_FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          REACT_APP_FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      - name: Deploy preview channel
        id: deploy
        run: |
          set -e
          # Run the `deploy:preview` script, passing the current git branch to be used for the name
          # of the preview channel
          yarn --cwd eisbuk-admin deploy:preview -- ${GITHUB_REF_SLUG_URL:-dev} | tee deploy.output
          # To pass the info to a later task, use the $GITHUB_ENV file
          cat deploy.output | grep 'hosting:channel:.*https://'|sed -e "s/\x1b\[[0-9;]*m//g;s|.*(||;s|)[^h]*|=|" >> $GITHUB_ENV
          # documented here: https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_EISBUK }}
      - name: Find Comment
        uses: peter-evans/find-comment@v1
        if: ${{ github.event.pull_request.number }}
        id: findcomment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-includes: Deployed URLs

      - name: Add preview channel URL to comment on PR
        uses: peter-evans/create-or-update-comment@v1
        if: ${{ github.event.pull_request.number }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          comment-id: ${{ steps.findcomment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Deployed URLs:
              * Igorice: ${{ env.igorice }}
              * Eisbuk: ${{ env.eisbuk }}
            ```
            ${{ env.BUILD_STATS }}
            ```
          reactions: heart, hooray, laugh, rocket
          edit-mode: replace

  test_v14:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Cache node modules and firebase emulators
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            $HOME/.cache/firebase/emulators
          key: ${{ runner.os }}-modules-emulators-v12-${{ hashFiles('**/yarn.lock') }}
      - name: Install and link packages
        run: yarn
      - name: Run tests
        run: yarn --cwd eisbuk-admin test:emulators:ci
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure() # Do not run on cancelled; run in all other cases
        with:
          name: JEST Tests
          path: eisbuk-admin/junit.xml
          reporter: jest-junit
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: eisbuk-admin/coverage/lcov.info

  run-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Cache node modules and firebase emulators
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            $HOME/.cache/firebase/emulators
          key: ${{ runner.os }}-modules-emulators-v12-${{ hashFiles('**/yarn.lock') }}
      - name: Install and link packages
        run: yarn
      - name: Lint client app
        run: "yarn --cwd eisbuk-admin lint:strict"
      - name: Lint eisbuk-shared
        # Do not run on cancelled; run in all other cases
        # We don't want a failed prevoius lint step to make this step not run
        if: success() || failure()
        run: "yarn --cwd eisbuk-shared lint:strict"
      - name: Lint the functions
        # Do not run on cancelled; run in all other cases
        # We don't want a failed prevoius lint step to make this step not run
        if: success() || failure()
        run: "yarn --cwd eisbuk-admin/functions lint:strict"
      - name: Typecheck the functions
        # Do not run on cancelled; run in all other cases
        # We don't want a failed lint steps to make this step not run
        if: success() || failure()
        run: "yarn --cwd eisbuk-admin/functions typecheck"

  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install-command: ./eisbuk-install.sh
          start: yarn start, yarn emulators:start
          working-directory: eisbuk-admin
