name: Build and deploy preview

on:
  - push
  - pull_request

jobs:
  build_v14:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Cache node modules and firebase emulators
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            $HOME/.cache/firebase/emulators
          key: ${{ runner.os }}-modules-emulators-v12-${{ hashFiles('**/yarn.lock') }}
      - name: Install and link packages
        run: ./eisbuk-install.sh
      - name: Build app
        run: yarn --cwd eisbuk-admin build
        env:
          REACT_APP_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          REACT_APP_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          REACT_APP_DATABASE_URL: ${{ secrets.DATABASE_URL }}
          REACT_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          REACT_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          REACT_APP_FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          REACT_APP_FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
      - name: Deploy preview channel
        run: |
          # Run the `deploy:preview` script, passing the current git branch to be used for the name
          # of the preview channel
          yarn --cwd eisbuk-admin deploy:preview -- $(git branch --show-current) |
            sed -E 's/^(...hosting:channel)/::debug::\1/'
          # and use a workflow command to make the deployed URLs more prominent
          # see https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-a-debug-message
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_EISBUK }}

  test_v14:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Cache node modules and firebase emulators
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            $HOME/.cache/firebase/emulators
          key: ${{ runner.os }}-modules-emulators-v12-${{ hashFiles('**/yarn.lock') }}
      - name: Install and link packages
        run: ./eisbuk-install.sh
      - name: Run tests
        run: yarn --cwd eisbuk-admin test:ci

  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7"
          architecture: "x64"
      - uses: pre-commit/action@v2.0.0
