name: "Deploy storybook"
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install requirements
        run: cd eisbuk-admin && yarn
      - name: build storybook and upload
        run: cd eisbuk-admin && npx chromatic --project-token=${{ secrets.CHROMAUI_PROJECT_TOKEN }}
