name: Deploy to production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    environment: Production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            $HOME/.cache/firebase/emulators
          key: ${{ runner.os }}-modules-v12-${{ hashFiles('**/yarn.lock') }}
      - name: Install and link packages
        run: yarn
      - name: Create .env file with credentials
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_REACT_APP_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          envkey_REACT_APP_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          envkey_REACT_APP_DATABASE_URL: ${{ secrets.DATABASE_URL }}
          envkey_REACT_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          envkey_REACT_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          envkey_REACT_APP_FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          envkey_REACT_APP_FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
          file_name: .env.production.local
      - name: Move .env file to eisbuk-admin
        run: mv .env.production.local eisbuk-admin
      - name: Build app
        run: yarn --cwd eisbuk-admin build
      - name: Deploy to firebase
        run: yarn --cwd eisbuk-admin deploy:production
        env: # Or as an environment variable
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_EISBUK }}
