name: Deploy to production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    environment: Production
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            $HOME/.cache/firebase/emulators
          key: ${{ runner.os }}-modules-v12-${{ hashFiles('**/yarn.lock') }}
      - name: Install and link packages
        run: yarn
      - name: Build app
        run: yarn --cwd eisbuk-admin build
        env:
          REACT_APP_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          REACT_APP_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          REACT_APP_DATABASE_URL: ${{ secrets.DATABASE_URL }}
          REACT_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          REACT_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          REACT_APP_FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          REACT_APP_FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
          REACT_APP_SENTRY_DSN: ${{ secrets.SENTRY_IGORICE_DSN }}
          REACT_APP_SENTRY_ENVIRONMENT: production
      - name: Deploy to firebase
        run: yarn --cwd eisbuk-admin deploy:production
        env: # Or as an environment variable
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_EISBUK }}
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: production
          sourcemaps: "./eisbuk-admin/dist/app"
