name: Tests

on: [push, pull_request]

jobs:
  test_v12:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
      - name: Cache node modules and firebase emulators
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            $HOME/.cache/firebase/emulators
          key: ${{ runner.os }}-modules-emulators-v12-${{ hashFiles('**/yarn.lock') }}
      - name: Install modules
        run: cd eisbuk-admin && yarn
      - name: Run tests
        run: cd eisbuk-admin && yarn test:ci
