name: Pre-commit

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7"
          architecture: "x64"
      - uses: pre-commit/action@v2.0.0
