name: Chromatic Storybook
"on":
- pull_request
jobs:
  storybook:
    name: Build storybook and push to Chromatic
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        node-version: "18"
    - name: Cache node modules and firebase emulators
      uses: actions/cache@v3
      with:
        path: |
          ~/.rush
          ~/.pnpm-store
          common/temp
          **/node_modules
          ~/.cache/firebase/emulators
        key: ${{ runner.os }}-modules-emulators-node18-v1-${{ hashFiles('**/pnpm-lock.yaml') }}
    - name: Add rush directory to PATH
      run: echo PATH=$PWD/common/scripts/:$PATH >> $GITHUB_ENV
    - name: Install and build packages
      run: rush update
    - name: Build packages
      run: rush build
    - name: Check if secrets are available
      id: has_secret
      if: success() || failure()
      run: '[ "${{ secrets.CYPRESS_KEY }}" != "" ] && echo HAS_SECRETS=true >> $GITHUB_OUTPUT || echo HAS_SECRETS= >> $GITHUB_OUTPUT'
    - name: Publish to Chromatic
      uses: chromaui/action@v1
      if: steps.has_secret.outputs.HAS_SECRETS
      continue-on-error: true
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        projectToken: ${{ secrets.CHROMAUI_PROJECT_TOKEN }}
        workingDir: packages/client
        exitZeroOnChanges: true
        exitOnceUploaded: true
