name: Storybook

on:
  - pull_request

jobs:
  storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-2-${{ hashFiles('**/yarn.lock') }}
      - name: Install and link packages
        run: yarn
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMAUI_PROJECT_TOKEN }}
          workingDir: eisbuk-admin
          exitZeroOnChanges: true
          exitOnceUploaded: true
